apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:latest
          envFrom:
            - secretRef:
                name: my-app-secrets
          env:
            - name: VAULT_SERVICE_NAME
              value: "vault-service-name-value"
