---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: xamma/python-vault:latest
          envFrom:
            - secretRef:
                name: my-app-secrets
          env:
            - name: VAULT_SERVICE_NAME
              value: vault.vault.svc.cluster.local
