---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: vault-test
spec:
  restartPolicy: Never
  containers:
    - name: my-app-container
      image: xamma/python-vault:latest
      envFrom:
        - secretRef:
            name: my-app-secrets
      env:
        - name: VAULT_SERVICE_NAME
          value: vault.vault.svc.cluster.local
